### ISSUE TITLE
Package PSM

### ISSUE THREAD

**Issue by chronoss09** [frangarcj/NoPsmDrm#2]
Can't use my PSM game without a package PSM, anyway to make the update ?
https://modconsoles.fr/uploads/monthly_2017_10/2017-10-15-064101.jpg.3f9f7a26f9e8fe9e986f65e49f3e15ee.jpg

https://modconsoles.fr/uploads/monthly_2017_10/2017-10-15-064105.jpg.bb4f3f2bc506774390cbeb228aa4b5c1.jpg

**Comment by Pauloedsonjk** [comment]
Check again readme. "Henkaku update server"

**Comment by frangarcj** [comment]
### Installing PSM runtime
When running a game for the first time, it will ask to install psm runtime. In order to download and install it, you need to change your DNS to [Henkaku Update Server](https://www.reddit.com/r/vitahacks/comments/5g819i/henkaku_update_server_easy_and_safe_way_to_update/)

**Comment by chronoss09** [comment]
Thanks but i have download the package in another way : https://modconsoles.fr/index.php?/forums/topic/707-installer-le-package-psm-sur-psvita-en-360/&tab=comments#comment-1751
If it can help you, no need DNS...
