### ISSUE TITLE
Bypass PSM Revocation Check,

### ISSUE THREAD

**Issue by SilicaAndPina** [frangarcj/NoPsmDrm#3]
enhancement:
Make this plugin set /CONFIG/PSM/revocation_check_req to 0 in registry.

you would just need to do something like:

    int ksceRegMgrSetKeyInt(const char*, const char*, int); //define ksceRegMgrSetKeyInt
    ksceRegMgrSetKeyInt("CONFIG/PSM", "revocation_check_req", 0); //set revocation_check_req to 0. 

if this value is set to 1 PSM runtime will connect to PSN to see if your "activated" this blocks you from playing PSM games offline, and can sometimes cause issues where the system just reboots unexpectedly.
setting it to 0 should resolve this issue.

**Comment by SilicaAndPina** [comment]
i made a mistake with my original code i wrote CONFIG/PSM instead of /CONFIG/PSM/ so what you put in doesnt acturally work :/ sorry about that

PS: your importing regmgr twice.

**Comment by frangarcj** [comment]
Fixed with 3d02fa30546a6cb50c444ef4a2e9de57ecb5767b
